resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:nbycomp/login-consent.git
      branch: master
      private_key: ((botnbycomp_private_key))

  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook))
    source:
      repository: nbycomp/login-consent
      access_token: ((github_access_key))

  - name: login-image
    type: registry-image
    source: {repository: ((registry))/nbycomp/core/auth/login-consent}

  - name: version
    type: semver
    source:
      driver: s3
      key: login-consent
      access_key_id: ((semver_access_key))
      secret_access_key:  ((semver_secret_key))
      bucket: nbycomp-pkg-vers
      region_name: eu-west-1

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - get: repo
        trigger: true
      - task: build
        file: repo/ci/build.yml
        privileged: true
        params: {REPOSITORY: ((registry))/nbycomp/core/auth/login-consent}
      - get: version
        params:
          bump: patch
      - put: login-image
        params:
          image: image/image.tar
          additional_tags: version/version
      - put: version
        params: {file: version/version}

  - name: test-pr
    public: true
    plan:
      - get: pull-request
        name: repo
        trigger: true
        version: every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - task: build
        file: repo/ci/build.yml
        privileged: true
        params: {REPOSITORY: ((registry))/nbycomp/core/auth/login-consent}
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success
